export const cardData = [
  {
    name: "Spaghetti",
    price: 12.05,
    category: "Dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Spaghetti.png",
  },
  {
    name: "Gnocchi",
    price: 12.05,
    category: "Lunch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Gnocchi.png",
  },
  {
    name: "Rovioli",
    price: 12.05,
    category: "Dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Rovioli.png",
  },
  {
    name: "Penne Alla Vodak",
    price: 12.05,
    category: "Lunch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Penne Alla Vodak.png",
  },
  {
    name: "Risoto",
    price: 12.05,
    category: "Dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Risoto.png",
  },
  {
    name: "Splitza Signature",
    price: 12.05,
    category: "Lunch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/Splitza Signature.png",
  },
  {
    name: "Chockalet Dount",
    price: 10.05,
    category: "Dessert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/ChockaletDount.png",
  },
  {
    name: "Classic Tiramisu",
    price: 10.05,
    category: "Dessert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/ClassicTiramisu.png",
  },
  {
    name: "Frosted Donut",
    price: 10.05,
    category: "Dessert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/FrostedDonut.png",
  },
  {
    name: "Sweet Cupcake",
    price: 10.05,
    category: "Dessert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/SweetCupcake.png",
  },
  {
    name: "Sprite",
    price: 7.05,
    category: "Drink",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/sprite.png",
  },
  {
    name: "Fanta",
    price: 7.05,
    category: "Drink",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/fanta.png",
  },
  {
    name: "Pepsi",
    price: 7.05,
    category: "Drink",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/pepsi.png",
  },
  {
    name: "Cocacola",
    price: 7.05,
    category: "Drink",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/cocacola.png",
  },
  {
    name: "Thums Up",
    price: 7.05,
    category: "Drink",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "/public/Assets/thumsUp.png",
  },
];
